
import { Product, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'All Products', icon: '🛒' },
  { id: 'khichdi', name: 'Khichdi & Biryani', icon: '🍲' },
  { id: 'oils', name: 'Pure Oils & Ghee', icon: '🍯' },
  { id: 'flours', name: 'Healthy Flours', icon: '🌾' },
  { id: 'pulses', name: 'Dals & Pulses', icon: '🍛' },
  { id: 'sweeteners', name: 'Natural Sweeteners', icon: '🍬' },
];

export const PRODUCTS: Product[] = [
  {
    id: 'k1',
    name: 'Organic Quinoa Khichdi',
    category: 'khichdi',
    price: 12.50,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?auto=format&fit=crop&q=80&w=400',
    description: 'A protein-packed blend of organic quinoa and split moong dal with traditional spices.',
    isPopular: true,
    calories: 180,
  },
  {
    id: 'k2',
    name: 'Organic Foxtail Millet Khichdi',
    category: 'khichdi',
    price: 10.99,
    unit: '500g',
    image: '',
    description: 'Rich in fiber and minerals, this foxtail millet khichdi is light on the stomach and heart-healthy.',
    calories: 165,
  },
  {
    id: 'o1',
    name: 'Pure Sunflower Oil',
    category: 'oils',
    price: 8.75,
    unit: '1L',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbadcbaf?auto=format&fit=crop&q=80&w=400',
    description: 'Cold-pressed organic sunflower oil, perfect for everyday healthy cooking.',
    calories: 120,
  },
  {
    id: 'o2',
    name: 'Wood-Pressed Groundnut Oil',
    category: 'oils',
    price: 14.20,
    unit: '1L',
    image: 'https://images.unsplash.com/photo-1589415445213-90768e71618d?auto=format&fit=crop&q=80&w=400',
    description: 'Authentic wood-pressed groundnut oil retaining all natural nutrients and nutty aroma.',
    isPopular: true,
    calories: 125,
  },
  {
    id: 's1',
    name: 'Pure Jaggery Powder',
    category: 'sweeteners',
    price: 5.40,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?auto=format&fit=crop&q=80&w=400',
    description: 'Chemical-free natural jaggery powder, a healthy substitute for refined sugar.',
    calories: 380,
  },
  {
    id: 's2',
    name: 'Organic Brown Sugar',
    category: 'sweeteners',
    price: 4.90,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1581441363689-1f3c3c414635?auto=format&fit=crop&q=80&w=400',
    description: 'Unrefined organic brown sugar with natural molasses flavor.',
    calories: 375,
  },
  {
    id: 'k3',
    name: 'Multi Millet Khichdi',
    category: 'khichdi',
    price: 11.50,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&q=80&w=400',
    description: 'A nutritious mix of five different millets and lentils for a balanced meal.',
    calories: 170,
  },
  {
    id: 'f1',
    name: 'Organic Jav (Barley) Flour',
    category: 'flours',
    price: 6.20,
    unit: '1kg',
    image: '',
    description: 'Stone-ground barley flour, excellent for weight management and digestion.',
    calories: 350,
  },
  {
    id: 'f2',
    name: 'Finger Millet (Ragi) Flour',
    category: 'flours',
    price: 5.80,
    unit: '1kg',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&q=80&w=400',
    description: 'Calcium-rich Ragi flour, perfect for making healthy rotis and porridges.',
    calories: 355,
  },
  {
    id: 'f3',
    name: 'Bajra (Pearl Millet) Flour',
    category: 'flours',
    price: 4.50,
    unit: '1kg',
    image: 'https://images.unsplash.com/photo-1541123437800-1bb1317badc2?auto=format&fit=crop&q=80&w=400',
    description: 'Traditional pearl millet flour, gluten-free and warming for winters.',
    calories: 360,
  },
  {
    id: 'f4',
    name: 'Whole Wheat Flour',
    category: 'flours',
    price: 3.99,
    unit: '1kg',
    image: 'https://images.unsplash.com/photo-1586444248902-2f64eddf13cf?auto=format&fit=crop&q=80&w=400',
    description: 'Premium Sharbati whole wheat flour, high in fiber and nutrition.',
    calories: 340,
  },
  {
    id: 'p1',
    name: 'Mix Dal Special',
    category: 'pulses',
    price: 7.20,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1585994192629-7a4f913f8c4d?auto=format&fit=crop&q=80&w=400',
    description: 'A perfect protein blend of Arhar, Moong, and Masoor dal.',
    calories: 345,
  },
  {
    id: 'p2',
    name: 'Premium Tuver Dal',
    category: 'pulses',
    price: 8.50,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1599059521327-048702c2e88a?auto=format&fit=crop&q=80&w=400',
    description: 'Unpolished Arhar dal with high natural protein content.',
    calories: 330,
  },
  {
    id: 'p3',
    name: 'Moong Chilka Dal',
    category: 'pulses',
    price: 6.80,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1585994192629-7a4f913f8c4d?auto=format&fit=crop&q=80&w=400',
    description: 'Split green gram with skin, highly digestible and nutritious.',
    calories: 310,
  },
  {
    id: 'p4',
    name: 'Organic Mung Dal',
    category: 'pulses',
    price: 6.50,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1585994192629-7a4f913f8c4d?auto=format&fit=crop&q=80&w=400',
    description: 'Yellow split mung bean, easy to cook and great for kids.',
    calories: 300,
  },
  {
    id: 'o3',
    name: 'Desi A2 Cow Ghee',
    category: 'oils',
    price: 35.00,
    unit: '500ml',
    image: 'https://images.unsplash.com/photo-1589927986089-35812388d1f4?auto=format&fit=crop&q=80&w=400',
    description: 'Traditional Bilona churned A2 Cow Ghee, pure and medicinal.',
    isPopular: true,
    calories: 900,
  },
  {
    id: 'p5',
    name: 'Desi Kala Chana',
    category: 'pulses',
    price: 5.20,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1515543904379-3d757afe72e2?auto=format&fit=crop&q=80&w=400',
    description: 'Small brown chickpeas, high in iron and protein.',
    calories: 360,
  },
  {
    id: 'k4',
    name: 'Kodo Millet Biryani Mix',
    category: 'khichdi',
    price: 13.99,
    unit: '500g',
    image: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&q=80&w=400',
    description: 'Healthy alternative to rice biryani, made with organic Kodo millet.',
    calories: 190,
  }
];
